[2023-01-02T10:16:55.333+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.extract scheduled__2023-01-02T10:11:52.871548+00:00 [queued]>
[2023-01-02T10:16:55.348+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.extract scheduled__2023-01-02T10:11:52.871548+00:00 [queued]>
[2023-01-02T10:16:55.350+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T10:16:55.352+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-02T10:16:55.353+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T10:16:55.369+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-01-02 10:11:52.871548+00:00
[2023-01-02T10:16:55.381+0000] {standard_task_runner.py:55} INFO - Started process 56 to run task
[2023-01-02T10:16:55.389+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'extract', 'scheduled__2023-01-02T10:11:52.871548+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmp3f3pewcc']
[2023-01-02T10:16:55.390+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask extract
[2023-01-02T10:16:55.465+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.extract scheduled__2023-01-02T10:11:52.871548+00:00 [running]> on host 64c425265806
[2023-01-02T10:16:55.558+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T10:11:52.871548+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T10:11:52.871548+00:00
[2023-01-02T10:16:55.771+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-02T10:16:55.912+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 56. PIDs of all processes in the group: [56]
[2023-01-02T10:16:55.913+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 56
[2023-01-02T10:16:55.957+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-02T10:16:56.680+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/team_stats.py", line 271, in extract
    player_stats = requests.get(f'https://api.sportsdata.io/v3/nba/stats/json/PlayerSeasonStats/2023?key={API_KEY}').json()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-02T10:16:57.995+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nba-dag, task_id=extract, execution_date=20230102T101152, start_date=20230102T101655, end_date=20230102T101657
[2023-01-02T10:17:00.789+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 70 for task extract (Task received SIGTERM signal; 56)
[2023-01-02T10:17:01.018+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=56, status='terminated', exitcode=1, started='10:16:55') (56) terminated with exit code 1
[2023-01-02T10:17:01.052+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-02T10:17:01.519+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
